# Generated by Django 5.2.7 on 2025-10-08 14:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_cliente_activo_alter_cliente_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='codigo_cliente',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='identificacion',
            field=models.CharField(max_length=50),
        ),
    ]
