# Generated by Django 5.2.7 on 2025-10-08 14:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_cliente_codigo_cliente_alter_cliente_identificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='codigo_cliente',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
