# Generated by Django 5.2.7 on 2025-10-08 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_alter_cliente_codigo_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fecha_eliminacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
