# Generated by Django 5.2.7 on 2025-10-08 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_cliente_fecha_eliminacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='telefono',
        ),
    ]
