# Generated by Django 5.2.7 on 2025-11-14 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_historialcliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioCreado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_usuarios_creados', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registro_de_creacion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
